### ISSUE TITLE
Advanced uses of relationship matchers?

### ISSUE THREAD

**Issue by ekampp** [teamintricately/rspec_jsonapi_serializer#4]
Hi there. 

Firstly: Thanks for a really nice gem!

I was wondering how I would go about testing that a particular relationship has a particular set of links or meta? 

E.g. In my serializer, I have:

```ruby
class User
  include JSONAPI::Serializer
  blog_posts_meta = lambda do |contest|
    {
      count: contest.candidates_count,
    }
  end
  blog_posts_links = {
    self: ->(u) { "/link/to/#{u.id}" },
  }
  has_many :blog_posts,
           meta: blog_posts_meta,
           links: blog_posts_links
end
```

Is there an in-built way that I can test that the association has the right links and the right meta block? 

Thanks in advance. 

Emil

**Comment by mateuscruz** [comment]
Hi @ekampp!

That's currently not possible. Each association option needs a specific sub-matcher, currently we have only 2 (`id_method_name` and `serializer`).

I'm not focused on this project at the moment so that may take me a while to write. However I'm sure if you open a PR my former coworkers at @teamintricately  will gladly review and release it. 

[`RSpecJSONAPISerializer::Matchers::AssociationMatcher`](https://github.com/teamintricately/rspec_jsonapi_serializer/blob/master/lib/rspec_jsonapi_serializer/matchers/association_matcher.rb) should give you a clue on how to implement it. You basically need to create a sub-matcher for each relationship option and then add an instance method in `AssociationMatcher` with the same name, which will add the sub-matcher to the instance.

**Comment by ekampp** [comment]
Hi, @mateuscruz. 

Thanks for the response! 

After some deliberation with my colleagues, we have decided on validating the resulting JSON instead.

I will close this PR.
